default:
  options:
    gfxbackend: gl
    video_threaded: true
    retroarch.video_rotation: 0 # for people upgrading
    retroarch.audio_driver: alsathread
    # menu retroarch
    retroarch.menu_scale_factor: "2.250000"
    retroarch.video_font_path: "/usr/share/fonts/truetype/nanum/NanumMyeongjo.ttf"

nds:
  emulator: libretro
  core:     drastic
fmtowns:
  emulator: libretro
  core:     mame
flash:
  emulator: lightspark
  core:     lightspark

